export default {
  login: 'victorsteven',
  id: 1,
  node_id: 'MDQ6VXNlcjE=',
  avatar_url: 'https://github.com/images/error/victorsteven_happy.gif',
  gravatar_id: '',
  url: 'https://api.github.com/users/victorsteven',
  html_url: 'https://github.com/victorsteven',
  followers_url: 'https://api.github.com/users/victorsteven/followers',
  following_url: 'https://api.github.com/users/victorsteven/following{/other_user}',
  gists_url: 'https://api.github.com/users/victorsteven/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/victorsteven/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/victorsteven/subscriptions',
  organizations_url: 'https://api.github.com/users/victorsteven/orgs',
  repos_url: 'https://api.github.com/users/victorsteven/repos',
  events_url: 'https://api.github.com/users/victorsteven/events{/privacy}',
  received_events_url: 'https://api.github.com/users/victorsteven/received_events',
  type: 'User',
  site_admin: false,
  name: 'Steven Victor',
  company: 'GitHub',
  blog: 'https://github.com/blog',
  location: 'Nigeria',
  email: 'victorsteven@github.com',
  hireable: false,
  bio: 'Web Developer',
  public_repos: 2,
  public_gists: 1,
  followers: 20,
  following: 0,
  created_at: '2017-01-14T04:33:35Z',
  updated_at: '2019-01-14T04:33:35Z',
};
